echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip
echo off | clip