; Generated by AutoGUI 1.4.9a
#NoEnv
;#Warn
#SingleInstance Force
SetWorkingDir %A_ScriptDir%


; GUI init setup

Menu Tray, Icon, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\favicon.ico

Gui Color, 0x9F0000
Gui Add, Picture, x8 y8 w400 h663, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\scorecard.png
Gui Add, Picture, x832 y8 w214 h94, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\yahtzeeLogo_gold.png
Gui Font, s30
Gui Add, Button, x584 y576 w280 h79, &Roll
Gui Font, s30
Gui Add, Button, x904 y576 w280 h80, &End Turn
Gui Font
Gui Add, Button, x1300 y10 w50 h20, E&xit
Gui Add, Button, x1245 y10 w50 h20, Re&set

Gui Show, w1366 h705, Yahtzee


;Gameplay

NewGame:
subTotal := 0
scoreTotal := 0
holdDice := ""
roll := 0
Gui Font, s20
Gui Add, Text, x500 y100 w152 h34 +0x200, Roll: %roll%

one := 0
two := 0
three := 0
four := 0
five := 0
six := 0
3OfKind := 0
4OfKind := 0
fullHs := 0
smStrt := 0
lgStrt := 0
chance := 0
yahtzee := 0

Gui Add, Picture, x456 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die1.png
Gui Add, Picture, x632 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die2.png
Gui Add, Picture, x808 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die3.png
Gui Add, Picture, x984 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die4.png
Gui Add, Picture, x1160 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die5.png

TurnStart:
holdDice := ""
roll := 0
; Gui Add, Picture, x456 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die1.png
; Gui Add, Picture, x632 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die2.png
; Gui Add, Picture, x808 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die3.png
; Gui Add, Picture, x984 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die4.png
; Gui Add, Picture, x1160 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die5.png
;return


;gLabels

ButtonRoll:
    If(roll>=3)
    {
        goto ButtonEndTurn
    }

	IfNotInString,holdDice,1
	{
		Random,die1,1,6
	}
	IfNotInString,holdDice,2
	{
		Random,die2,1,6
	}
	IfNotInString,holdDice,3
	{
		Random,die3,1,6
	}
	IfNotInString,holdDice,4
	{
		Random,die4,1,6
	}
	IfNotInString,holdDice,5
	{
		Random,die5,1,6
	}

    i := 0
    holdAll := 0
    Loop, 5
    {
        ++i
        IfInString,holdDice,%i%
        {
            ++holdAll
        }
    }
    If (holdAll=5)
    {
        MsgBox, You are holding all your dice!
        Return
    }

    Gui Add, Picture, x456 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die%die1%.png
    Gui Add, Picture, x632 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die%die2%.png
    Gui Add, Picture, x808 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die%die3%.png
    Gui Add, Picture, x984 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die%die4%.png
    Gui Add, Picture, x1160 y350 h168 h168, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\die%die5%.png

    Gui Font, s10
    Gui Add, Button, x525 y520 w30 h20 gDie1Hold, &1
    Gui Add, Button, x701 y520 w30 h20 gDie2Hold, &2
    Gui Add, Button, x877 y520 w30 h20 gDie3Hold, &3
    Gui Add, Button, x1053 y520 w30 h20 gDie4Hold, &4
    Gui Add, Button, x1229 y520 w30 h20 gDie5Hold, &5

    ++roll
    Gui Font, s20
    Gui Add, Text, x500 y100 w152 h34 +0x200, Roll: %roll%
    Gui Font
Return

Die1Hold:
    IfNotInString,holdDice,1
    {
        holdDice := holdDice 1
        Gui Add, Picture, x451 y345 h173 h4, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\dieHoldX.png
        Gui Add, Picture, x451 y518 h173 h4, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\dieHoldX.png
        Gui Add, Picture, x451 y345 h4 h173, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\dieHoldY.png
        Gui Add, Picture, x624 y345 h4 h173, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\dieHoldY.png
    }
    Else
    {
        StringReplace,holdDice,holdDice,1,,All
        Gui Add, Picture, x451 y345 h173 h4, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\dieUnholdX.png
        Gui Add, Picture, x451 y518 h173 h4, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\dieUnholdX.png
        Gui Add, Picture, x451 y345 h4 h173, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\dieUnholdY.png
        Gui Add, Picture, x624 y345 h4 h173, D:\Users\mjrinker\Google Drive\Documents\Other\AutoHotKey Scripts\Yahtzee\gui\pic\dieUnholdY.png
    }
Return

Die1Unhold:
    StringReplace,holdDice,holdDice,1,,All
Return

Die2Hold:
    holdDice := holdDice 2
Return

Die2Unhold:
    StringReplace,holdDice,holdDice,2,,All
Return

Die3Hold:
    holdDice := holdDice 3
Return

Die3Unhold:
    StringReplace,holdDice,holdDice,3,,All
Return

Die4Hold:
    holdDice := holdDice 4
Return

Die4Unhold:
    StringReplace,holdDice,holdDice,4,,All
Return

Die5Hold:
    holdDice := holdDice 5
Return

Die5Unhold:
    StringReplace,holdDice,holdDice,5,,All
Return

ButtonEndTurn:
    goto TurnStart
Return

ButtonReset:
    goto NewGame

ButtonExit:
    ExitApp


; HotKeys

^del::
    goto ButtonExit
Return

!F4::
    goto ButtonExit
Return