; Generated by AutoGUI 1.4.9a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Font, s20
Gui Add, Text, x120 y16 w152 h34 +0x200, High Scores
Gui Font

Gui Show, w400 h300, Window
Return

GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line