; Generated by AutoGUI 1.4.9a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Font, s20
Gui Add, Button, x100 y72 w200 h45, &Play
Gui Font
Gui Font, s10
Gui Add, Button, x112 y130 w176 h30, &High Scores
Gui Font
Gui Font, s10
Gui Add, Button, x112 y210 w176 h30, &Settings
Gui Font
Gui Font, s10
Gui Add, Button, x112 y170 w176 h30, &Rules
Gui Font
Gui Font, s10
Gui Add, Button, x112 y250 w176 h30, &Quit
Gui Font
Gui Add, Text, x194 y37 w0 h0 +0x200, Text
Gui Add, Picture, x131 y5 w137 h60, %A_ScriptDir%\pic\yahtzeeLogo.png

Gui Show, w400 h300, Yahtzee - Main Menu
Return

ButtonPlay: 
    Run, name.ahk
    ExitApp
Return

ButtonHighScores:
    Run, highScores.ahk
    ExitApp
Return

ButtonSettings:
    Run, settings.ahk
    ExitApp
Return

ButtonRules:
    Run, rules.ahk
    ExitApp
Return

ButtonQuit:
GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line