; Generated by AutoGUI 1.4.9a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Font, s13
Gui Add, Edit, x40 y64 w241 h26
Gui Font
Gui Font, s10
Gui Add, Button, x175 y120 w80 h23, &Continue
Gui Font
Gui Font, s16
Gui Add, Text, x40 y24 w196 h32 +0x200, What is your name?
Gui Font
Gui Font, s10
Gui Add, Button, x64 y120 w80 h23, &Back
Gui Font

Gui Show, w313 h179, Window
Return

GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line